model_list:
  - model_name: bunker-agent
    litellm_params:
      model: openai/qwen3-coder-30b-awq
      api_base: http://vllm-engine:8000/v1
      api_key: sk-1234 # Key interna entre LiteLLM y vLLM
      drop_params: True
      enable_tool_calling: True
      stream: true
      # Par√°metros recomendados para Qwen3-Coder
      temperature: 0.7
      top_p: 0.8
      top_k: 20
      repetition_penalty: 1.05

litellm_settings:
  drop_params: True
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
